if(EXISTS "/opt/apollo/contrib/hephaestus/test/unit/unit_tests[1]_tests.cmake")
  include("/opt/apollo/contrib/hephaestus/test/unit/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
