if(EXISTS "/opt/apollo/contrib/hephaestus/test/integration/integration_tests[1]_tests.cmake")
  include("/opt/apollo/contrib/hephaestus/test/integration/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
